linters:
  enable:
    - errcheck      # check error returns
    - govet         # suspicious constructs
    - staticcheck   # advanced static analysis
    - unused        # unused code
    - gosimple      # simplifications
    - ineffassign   # useless assignments
    - misspell      # spelling mistakes
    - gocritic      # opinionated lints
    - revive        # replacement for golint
    - unconvert     # unnecessary type conversions
    - prealloc      # slice preallocation hints
    - bodyclose     # http response body not closed
    - noctx         # http requests without context
    - gosec         # security issues
    - errorlint     # error wrapping and comparison
    - gocognit      # cognitive complexity
    - nilnil        # return nil, nil
    - wastedassign  # assignments to variables never read
    - tenv          # os.Setenv in tests instead of t.Setenv

linters-settings:
  govet:
    enable-all: true
  errcheck:
    check-blank: false
  revive:
    rules:
      - name: exported
        arguments: [checkPrivateReceivers]
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  gosec:
    excludes:
      - G104  # errcheck covers this
      - G304  # sif reads user-supplied wordlist paths — intentional
  gocognit:
    min-complexity: 30

run:
  timeout: 5m
  issues-exit-code: 1

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
